### ISSUE TITLE
Docker nedir?

### ISSUE THREAD

**Issue by farukerdem34** [skylab-kulubu/skycloud#1]

**Comment by izzatmammadzada** [comment]
Docker uygulamalari izole bir ortamda calistirmak icin kullanilan bi konteyner teknolojisidir. Sanal makinelere benzer ama daha iyidir. Bir uygulama icin sanal makine kurmak o kadar da iyi bi secim degil cunku bilgisyarin gucunu ayiriyor. Docker ise konteynerler sayesinde uygulamalari hafif sekilde calistiriyor. Ayrica uygulama paketleme ve dagitimi konusunda da kolaylik sagliyor, Her sey bir arada oluyor ve baska birisi ayni uygulamayi kendi bilgisayarinda kolaylikla calistira biliyor.
